In [2]:
import torch

In [5]:
A = torch.tensor([1,2,3,4,5])
B = torch.tensor([10,20,30])

C, D = torch.meshgrid(A, B, indexing='ij')
print(C)
print(D)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])
tensor([[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]])


In [9]:
C_s = C.flatten()
D_s = D.flatten()

print(C_s)
print(D_s)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])
tensor([10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30])


In [10]:
shifts = torch.stack((C_s, D_s, C_s, D_s), dim=1)
print(shifts)

tensor([[ 1, 10,  1, 10],
        [ 1, 20,  1, 20],
        [ 1, 30,  1, 30],
        [ 2, 10,  2, 10],
        [ 2, 20,  2, 20],
        [ 2, 30,  2, 30],
        [ 3, 10,  3, 10],
        [ 3, 20,  3, 20],
        [ 3, 30,  3, 30],
        [ 4, 10,  4, 10],
        [ 4, 20,  4, 20],
        [ 4, 30,  4, 30],
        [ 5, 10,  5, 10],
        [ 5, 20,  5, 20],
        [ 5, 30,  5, 30]])


In [ ]:
torch.view()

In [13]:
from rpn import RegionProposalNetwork as rpn_conv

model = rpn_conv()

image = torch.randn(1, 3, 600, 800)
feat = torch.randn(1, 512, 37, 50)
anchors = model.generate_anchors(image, feat)
print(anchors.shape)

torch.Size([16650, 4])


In [14]:
anchors[:10]

tensor([[ -91.,  -45.,   91.,   45.],
        [-181.,  -91.,  181.,   91.],
        [-362., -181.,  362.,  181.],
        [ -64.,  -64.,   64.,   64.],
        [-128., -128.,  128.,  128.],
        [-256., -256.,  256.,  256.],
        [ -45.,  -91.,   45.,   91.],
        [ -91., -181.,   91.,  181.],
        [-181., -362.,  181.,  362.],
        [ -91.,  -29.,   91.,   61.]])

In [18]:
A = torch.arange(0, 120).view(2, 3, 4, 5)
A

tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])

In [21]:
A.reshape(-1, 1)

tensor([[  0],
        [  1],
        [  2],
        [  3],
        [  4],
        [  5],
        [  6],
        [  7],
        [  8],
        [  9],
        [ 10],
        [ 11],
        [ 12],
        [ 13],
        [ 14],
        [ 15],
        [ 16],
        [ 17],
        [ 18],
        [ 19],
        [ 20],
        [ 21],
        [ 22],
        [ 23],
        [ 24],
        [ 25],
        [ 26],
        [ 27],
        [ 28],
        [ 29],
        [ 30],
        [ 31],
        [ 32],
        [ 33],
        [ 34],
        [ 35],
        [ 36],
        [ 37],
        [ 38],
        [ 39],
        [ 40],
        [ 41],
        [ 42],
        [ 43],
        [ 44],
        [ 45],
        [ 46],
        [ 47],
        [ 48],
        [ 49],
        [ 50],
        [ 51],
        [ 52],
        [ 53],
        [ 54],
        [ 55],
        [ 56],
        [ 57],
        [ 58],
        [ 59],
        [ 60],
        [ 61],
        [ 62],
        [ 63],
        [ 64],
        [ 65],
        [ 

In [20]:
A.permute(0,2,3,1).reshape(-1,1)

tensor([[  0],
        [ 20],
        [ 40],
        [  1],
        [ 21],
        [ 41],
        [  2],
        [ 22],
        [ 42],
        [  3],
        [ 23],
        [ 43],
        [  4],
        [ 24],
        [ 44],
        [  5],
        [ 25],
        [ 45],
        [  6],
        [ 26],
        [ 46],
        [  7],
        [ 27],
        [ 47],
        [  8],
        [ 28],
        [ 48],
        [  9],
        [ 29],
        [ 49],
        [ 10],
        [ 30],
        [ 50],
        [ 11],
        [ 31],
        [ 51],
        [ 12],
        [ 32],
        [ 52],
        [ 13],
        [ 33],
        [ 53],
        [ 14],
        [ 34],
        [ 54],
        [ 15],
        [ 35],
        [ 55],
        [ 16],
        [ 36],
        [ 56],
        [ 17],
        [ 37],
        [ 57],
        [ 18],
        [ 38],
        [ 58],
        [ 19],
        [ 39],
        [ 59],
        [ 60],
        [ 80],
        [100],
        [ 61],
        [ 81],
        [101],
        [ 

In [23]:
x = torch.tensor([1, 2, 3, 4, 10])
x.topk(3)

torch.return_types.topk(
values=tensor([10,  4,  3]),
indices=tensor([4, 3, 2]))

In [26]:
torch.zeros_like(x, dtype=torch.bool)

tensor([False, False, False, False, False])

In [35]:
a = torch.tensor([[1, 2], [3, 4], [10, 20]])
b = torch.tensor([[5, 6], [7, 8]])
aa = a[:, None, 1]
bb = b[:,1]
print(aa.shape)
print(bb.shape)

torch.Size([3, 1])
torch.Size([2])


In [36]:
torch.max(aa, bb)

tensor([[ 6,  8],
        [ 6,  8],
        [20, 20]])

In [42]:
torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]).max(dim=0)

torch.return_types.max(
values=tensor([ 6,  7,  8,  9, 10]),
indices=tensor([1, 1, 1, 1, 1]))

In [48]:
cc = torch.tensor([[1,2,1,4,5],[1,7,8,1,10]])
dd = torch.tensor([1,1])

torch.where(cc == dd[:, None])

(tensor([0, 0, 1, 1]), tensor([0, 2, 0, 3]))

In [49]:
torch.where(cc == dd[:, None], 1, 0)

tensor([[1, 0, 1, 0, 0],
        [1, 0, 0, 1, 0]])

In [4]:
true_place = torch.tensor([1,0,1,0,1,1], dtype=torch.bool)

In [7]:
torch.where(true_place)[0]

tensor([0, 2, 4, 5])